name: digital_menu
description: A Flutter app for Digital Menu.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.4
  google_fonts: ^6.2.1
  permission_handler: ^11.3.1
  qr_flutter: ^4.1.0
  http: ^1.4.0
  intl: ^0.20.2
  shared_preferences: ^2.1.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  mobile_scanner: ^3.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true  # Enable localization generation
  assets:
    - assets/logo/app_logo.png
    - assets/home/banner.png
    
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/logo/app_logo.png
