name: digital_menu
description: A Flutter app for Digital Menu.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.4
  google_fonts: ^6.2.1
  permission_handler: ^11.3.1
  qr_flutter: ^4.1.0
  http: ^1.4.0
  shared_preferences: ^2.2.3
  intl: ^0.20.2
  image_picker_web: ^3.0.0
  universal_html: ^2.2.1
  mobile_scanner: ^3.5.5
  dio: ^5.9.0
  # csv: ^5.0.2
  path_provider: ^2.1.3
  device_info_plus: ^9.1.2
  excel: ^4.0.6 
  pdf: ^3.10.8   # Added for PDF report
  open_filex: ^4.3.4  # Added for opening files
  flutter_animate: ^4.5.2
  simple_animations: ^5.2.0
  # file_saver: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo/app_logo.png
    - assets/home/banner.png
    - fonts/Poppins-Regular.ttf
    - fonts/Montserrat-Regular.ttf
    - fonts/Roboto-Regular.ttf
    - fonts/OpenSans-Regular.ttf
    - fonts/Lato-Regular.ttf
    - fonts/Nunito-Regular.ttf
    - fonts/Inter-Regular.ttf
    - fonts/Raleway-Regular.ttf
    - fonts/Ubuntu-Regular.ttf
    - fonts/SourceSansPro-Regular.ttf

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
    - family: Open Sans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf
    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/app_logo.png"






